sonar.projectKey=sapientpants_quorum
sonar.organization=sapientpants

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=quorum
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
sonar.sources=src
sonar.exclusions=**/node_modules/**,src/assets/**/*,dist/**
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.testExecutionReportPaths=sonar-report.xml
sonar.typescript.lcov.reportPaths=coverage/lcov.info